-- migrate:up transaction:false

CREATE EXTENSION IF NOT EXISTS timescaledb;
COMMENT ON EXTENSION timescaledb IS
  'Time-series extension; market.candles is a hypertable partitioned on time';

CREATE SCHEMA IF NOT EXISTS solana;
COMMENT ON SCHEMA solana IS 'Solana mints and GeckoTerminal pools used to resolve WATCHLIST pairs';

CREATE SCHEMA IF NOT EXISTS market;
COMMENT ON SCHEMA market IS 'Shared OHLCV cache and per-bot strategy signals';

CREATE SCHEMA IF NOT EXISTS bot;
COMMENT ON SCHEMA bot IS 'Paper and live portfolio ledgers, isolated by bot_id';

DO $$ BEGIN
  CREATE TYPE market.timeframe AS ENUM ('15m', '4h', '1d');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
COMMENT ON TYPE market.timeframe IS 'OHLCV bar size: 15m strategy bars, 4h/1d higher-timeframe bars';

DO $$ BEGIN
  CREATE TYPE bot.mode AS ENUM ('paper', 'live');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
COMMENT ON TYPE bot.mode IS 'Ledger kind: paper (simulated fills) or live (on-chain Jupiter swaps)';

CREATE TABLE IF NOT EXISTS solana.tokens (
  mint     TEXT NOT NULL PRIMARY KEY,
  symbol   TEXT NOT NULL UNIQUE,
  decimals INTEGER NOT NULL
);
COMMENT ON TABLE solana.tokens IS 'SPL token mint, ticker, and decimals';
COMMENT ON COLUMN solana.tokens.mint IS 'Base58 mint address (primary key)';
COMMENT ON COLUMN solana.tokens.symbol IS 'Ticker used in WATCHLIST pairs (e.g. SOL)';
COMMENT ON COLUMN solana.tokens.decimals IS 'SPL token decimals for UI ↔ atomic conversion';
COMMENT ON CONSTRAINT tokens_pkey ON solana.tokens IS 'Primary key on mint';
COMMENT ON CONSTRAINT tokens_symbol_key ON solana.tokens IS 'One row per ticker';

CREATE TABLE IF NOT EXISTS solana.pools (
  address    TEXT NOT NULL PRIMARY KEY,
  base_mint  TEXT NOT NULL REFERENCES solana.tokens (mint),
  quote_mint TEXT NOT NULL REFERENCES solana.tokens (mint),
  UNIQUE (base_mint, quote_mint)
);
COMMENT ON TABLE solana.pools IS 'GeckoTerminal pool for a unique base/quote mint pair';
COMMENT ON COLUMN solana.pools.address IS 'GeckoTerminal / AMM pool address';
COMMENT ON COLUMN solana.pools.base_mint IS 'Base token mint (WATCHLIST left side)';
COMMENT ON COLUMN solana.pools.quote_mint IS 'Quote token mint (WATCHLIST right side)';
COMMENT ON CONSTRAINT pools_pkey ON solana.pools IS 'Primary key on pool address';
COMMENT ON CONSTRAINT pools_base_mint_quote_mint_key ON solana.pools IS
  'At most one pool per base/quote mint pair';
COMMENT ON CONSTRAINT pools_base_mint_fkey ON solana.pools IS 'Base mint must exist in solana.tokens';
COMMENT ON CONSTRAINT pools_quote_mint_fkey ON solana.pools IS 'Quote mint must exist in solana.tokens';

CREATE TABLE IF NOT EXISTS market.candles (
  pool_address TEXT              NOT NULL REFERENCES solana.pools (address),
  timeframe    market.timeframe  NOT NULL,
  time         TIMESTAMPTZ       NOT NULL,
  open         DOUBLE PRECISION NOT NULL,
  high         DOUBLE PRECISION NOT NULL,
  low          DOUBLE PRECISION NOT NULL,
  close        DOUBLE PRECISION NOT NULL,
  volume       DOUBLE PRECISION NOT NULL,
  fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (pool_address, timeframe, time)
);
COMMENT ON TABLE market.candles IS
  'Timescale hypertable of OHLCV bars keyed by pool, timeframe, and open time';
COMMENT ON COLUMN market.candles.pool_address IS 'solana.pools address this series belongs to';
COMMENT ON COLUMN market.candles.timeframe IS 'Bar size (15m, 4h, or 1d)';
COMMENT ON COLUMN market.candles.time IS 'Candle open time (UTC)';
COMMENT ON COLUMN market.candles.open IS 'Open price in quote units';
COMMENT ON COLUMN market.candles.high IS 'High price in quote units';
COMMENT ON COLUMN market.candles.low IS 'Low price in quote units';
COMMENT ON COLUMN market.candles.close IS 'Close price in quote units';
COMMENT ON COLUMN market.candles.volume IS 'Traded volume on this bar';
COMMENT ON COLUMN market.candles.fetched_at IS 'When this bar was last written from GeckoTerminal';
COMMENT ON CONSTRAINT candles_pkey ON market.candles IS
  'One bar per pool, timeframe, and open time';
COMMENT ON CONSTRAINT candles_pool_address_fkey ON market.candles IS
  'Candle pool must exist in solana.pools';

SELECT create_hypertable('market.candles', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS candles_pool_tf_time_idx
  ON market.candles (pool_address, timeframe, time DESC);
COMMENT ON INDEX market.candles_pool_tf_time_idx IS
  'Lookup latest bars for a pool and timeframe';

CREATE TABLE IF NOT EXISTS market.signals (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id    TEXT        NOT NULL,
  "at"      TIMESTAMPTZ NOT NULL,
  pair      TEXT        NOT NULL,
  side      TEXT        NOT NULL,
  price     DOUBLE PRECISION NOT NULL,
  reason    TEXT        NOT NULL,
  ema_fast  DOUBLE PRECISION,
  ema_slow  DOUBLE PRECISION,
  rsi       DOUBLE PRECISION,
  trend_ema DOUBLE PRECISION,
  atr       DOUBLE PRECISION,
  adx       DOUBLE PRECISION
);
COMMENT ON TABLE market.signals IS 'Strategy BUY/SELL/HOLD emissions scoped by bot_id';
COMMENT ON COLUMN market.signals.id IS 'Identity primary key';
COMMENT ON COLUMN market.signals.bot_id IS 'BOT_ID of the process that emitted this signal';
COMMENT ON COLUMN market.signals."at" IS 'Signal timestamp (UTC)';
COMMENT ON COLUMN market.signals.pair IS 'WATCHLIST pair (e.g. SOL/USDC)';
COMMENT ON COLUMN market.signals.side IS 'BUY, SELL, or HOLD';
COMMENT ON COLUMN market.signals.price IS 'Mark price at signal time';
COMMENT ON COLUMN market.signals.reason IS 'Human-readable strategy reason';
COMMENT ON COLUMN market.signals.ema_fast IS 'Optional fast EMA from signal meta';
COMMENT ON COLUMN market.signals.ema_slow IS 'Optional slow EMA from signal meta';
COMMENT ON COLUMN market.signals.rsi IS 'Optional RSI from signal meta';
COMMENT ON COLUMN market.signals.trend_ema IS 'Optional trend EMA from signal meta';
COMMENT ON COLUMN market.signals.atr IS 'Optional ATR from signal meta';
COMMENT ON COLUMN market.signals.adx IS 'Optional ADX from signal meta';
COMMENT ON CONSTRAINT signals_pkey ON market.signals IS 'Primary key on id';
COMMENT ON SEQUENCE market.signals_id_seq IS 'Identity sequence for market.signals.id';

CREATE UNIQUE INDEX IF NOT EXISTS signals_bot_pair_at_uidx
  ON market.signals (bot_id, pair, "at");
COMMENT ON INDEX market.signals_bot_pair_at_uidx IS
  'Idempotent insert key: one signal per bot, pair, and timestamp';

CREATE INDEX IF NOT EXISTS signals_bot_at_idx ON market.signals (bot_id, "at" DESC);
COMMENT ON INDEX market.signals_bot_at_idx IS 'List a bot''s signals newest first';

CREATE TABLE IF NOT EXISTS bot.portfolios (
  bot_id         TEXT        NOT NULL,
  mode           bot.mode    NOT NULL,
  pair           TEXT        NOT NULL,
  cash_usdc      DOUBLE PRECISION NOT NULL,
  realized_pnl   DOUBLE PRECISION NOT NULL,
  position_side  TEXT        NOT NULL,
  position_size  DOUBLE PRECISION NOT NULL,
  entry_price    DOUBLE PRECISION NOT NULL,
  opened_at      TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (bot_id, mode, pair)
);
COMMENT ON TABLE bot.portfolios IS
  'One open position snapshot per bot, mode (paper/live), and pair';
COMMENT ON COLUMN bot.portfolios.bot_id IS 'BOT_ID that owns this ledger row';
COMMENT ON COLUMN bot.portfolios.mode IS 'paper (simulated) or live (on-chain)';
COMMENT ON COLUMN bot.portfolios.pair IS 'WATCHLIST pair (e.g. SOL/USDC)';
COMMENT ON COLUMN bot.portfolios.cash_usdc IS 'Quote cash balance in USDC';
COMMENT ON COLUMN bot.portfolios.realized_pnl IS 'Cumulative realized PnL in USDC';
COMMENT ON COLUMN bot.portfolios.position_side IS 'flat or long';
COMMENT ON COLUMN bot.portfolios.position_size IS 'Base size of the open long (0 if flat)';
COMMENT ON COLUMN bot.portfolios.entry_price IS 'Average entry price of the open long';
COMMENT ON COLUMN bot.portfolios.opened_at IS 'When the current long was opened (null if flat)';
COMMENT ON COLUMN bot.portfolios.updated_at IS 'Last ledger write time (UTC)';
COMMENT ON CONSTRAINT portfolios_pkey ON bot.portfolios IS
  'One portfolio row per bot, mode, and pair';

CREATE TABLE IF NOT EXISTS bot.trades (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id       TEXT        NOT NULL,
  mode         bot.mode    NOT NULL,
  pair         TEXT        NOT NULL,
  side         TEXT        NOT NULL,
  price        DOUBLE PRECISION NOT NULL,
  size         DOUBLE PRECISION NOT NULL,
  realized_pnl DOUBLE PRECISION,
  "at"         TIMESTAMPTZ NOT NULL,
  simulated    BOOLEAN     NOT NULL,
  tx_signature TEXT
);
COMMENT ON TABLE bot.trades IS 'Fill history for paper and live ledgers';
COMMENT ON COLUMN bot.trades.id IS 'Identity primary key';
COMMENT ON COLUMN bot.trades.bot_id IS 'BOT_ID that owns this fill';
COMMENT ON COLUMN bot.trades.mode IS 'paper (simulated) or live (on-chain)';
COMMENT ON COLUMN bot.trades.pair IS 'WATCHLIST pair (e.g. SOL/USDC)';
COMMENT ON COLUMN bot.trades.side IS 'BUY or SELL';
COMMENT ON COLUMN bot.trades.price IS 'Fill price in quote units';
COMMENT ON COLUMN bot.trades.size IS 'Fill size in base units';
COMMENT ON COLUMN bot.trades.realized_pnl IS 'Realized PnL on this fill, if any';
COMMENT ON COLUMN bot.trades."at" IS 'Fill timestamp (UTC)';
COMMENT ON COLUMN bot.trades.simulated IS 'true for paper/backtest fills; false for live Jupiter swaps';
COMMENT ON COLUMN bot.trades.tx_signature IS 'Solana signature for live fills (null if simulated)';
COMMENT ON CONSTRAINT trades_pkey ON bot.trades IS 'Primary key on id';
COMMENT ON SEQUENCE bot.trades_id_seq IS 'Identity sequence for bot.trades.id';

CREATE INDEX IF NOT EXISTS trades_bot_mode_pair_idx ON bot.trades (bot_id, mode, pair);
COMMENT ON INDEX bot.trades_bot_mode_pair_idx IS 'Load fills for a bot ledger pair';

INSERT INTO solana.tokens (mint, symbol, decimals)
VALUES
  ('So11111111111111111111111111111111111111112', 'SOL', 9),
  ('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v', 'USDC', 6),
  ('JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN', 'JUP', 6),
  ('jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL', 'JTO', 9)
ON CONFLICT (mint) DO NOTHING;

INSERT INTO solana.pools (address, base_mint, quote_mint)
VALUES
  (
    '8sLbNZoA1cfnvMJLPfp98ZLAnFSYCFApfJKMbiXNLwxj',
    'So11111111111111111111111111111111111111112',
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  ),
  (
    'HfgjZDmexhFVD28Vkb1NbQwWeXP3uDcVTLPjSGHmRHhL',
    'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  ),
  (
    '93MjUKNKxazKmgS3GBX2Gj2BttEjJUyi7NYeyDHdHSc2',
    'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  )
ON CONFLICT (address) DO NOTHING;

-- migrate:down

DROP SCHEMA IF EXISTS bot CASCADE;
DROP SCHEMA IF EXISTS market CASCADE;
DROP SCHEMA IF EXISTS solana CASCADE;
