CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE SCHEMA IF NOT EXISTS solana;
CREATE SCHEMA IF NOT EXISTS market;
CREATE SCHEMA IF NOT EXISTS bot;

DO $$ BEGIN
  CREATE TYPE market.timeframe AS ENUM ('15m', '4h', '1d');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE bot.mode AS ENUM ('paper', 'live');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS solana.tokens (
  mint     TEXT NOT NULL PRIMARY KEY,
  symbol   TEXT NOT NULL UNIQUE,
  decimals INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS solana.pools (
  address    TEXT NOT NULL PRIMARY KEY,
  base_mint  TEXT NOT NULL REFERENCES solana.tokens (mint),
  quote_mint TEXT NOT NULL REFERENCES solana.tokens (mint),
  UNIQUE (base_mint, quote_mint)
);

CREATE TABLE IF NOT EXISTS market.candles (
  pool_address TEXT              NOT NULL REFERENCES solana.pools (address),
  timeframe    market.timeframe  NOT NULL,
  time         TIMESTAMPTZ       NOT NULL,
  open         DOUBLE PRECISION NOT NULL,
  high         DOUBLE PRECISION NOT NULL,
  low          DOUBLE PRECISION NOT NULL,
  close        DOUBLE PRECISION NOT NULL,
  volume       DOUBLE PRECISION NOT NULL,
  fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (pool_address, timeframe, time)
);

SELECT create_hypertable('market.candles', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS candles_pool_tf_time_idx
  ON market.candles (pool_address, timeframe, time DESC);

CREATE TABLE IF NOT EXISTS market.signals (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id    TEXT        NOT NULL,
  "at"      TIMESTAMPTZ NOT NULL,
  pair      TEXT        NOT NULL,
  side      TEXT        NOT NULL,
  price     DOUBLE PRECISION NOT NULL,
  reason    TEXT        NOT NULL,
  ema_fast  DOUBLE PRECISION,
  ema_slow  DOUBLE PRECISION,
  rsi       DOUBLE PRECISION,
  trend_ema DOUBLE PRECISION,
  atr       DOUBLE PRECISION,
  adx       DOUBLE PRECISION
);

CREATE UNIQUE INDEX IF NOT EXISTS signals_bot_pair_at_uidx
  ON market.signals (bot_id, pair, "at");

CREATE INDEX IF NOT EXISTS signals_bot_at_idx ON market.signals (bot_id, "at" DESC);

CREATE TABLE IF NOT EXISTS bot.portfolios (
  bot_id         TEXT        NOT NULL,
  mode           bot.mode    NOT NULL,
  pair           TEXT        NOT NULL,
  cash_usdc      DOUBLE PRECISION NOT NULL,
  realized_pnl   DOUBLE PRECISION NOT NULL,
  position_side  TEXT        NOT NULL,
  position_size  DOUBLE PRECISION NOT NULL,
  entry_price    DOUBLE PRECISION NOT NULL,
  opened_at      TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (bot_id, mode, pair)
);

CREATE TABLE IF NOT EXISTS bot.trades (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id       TEXT        NOT NULL,
  mode         bot.mode    NOT NULL,
  pair         TEXT        NOT NULL,
  side         TEXT        NOT NULL,
  price        DOUBLE PRECISION NOT NULL,
  size         DOUBLE PRECISION NOT NULL,
  realized_pnl DOUBLE PRECISION,
  "at"         TIMESTAMPTZ NOT NULL,
  simulated    BOOLEAN     NOT NULL,
  tx_signature TEXT
);

CREATE INDEX IF NOT EXISTS trades_bot_mode_pair_idx ON bot.trades (bot_id, mode, pair);

INSERT INTO solana.tokens (mint, symbol, decimals)
VALUES
  ('So11111111111111111111111111111111111111112', 'SOL', 9),
  ('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v', 'USDC', 6),
  ('JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN', 'JUP', 6),
  ('jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL', 'JTO', 9)
ON CONFLICT (mint) DO NOTHING;

INSERT INTO solana.pools (address, base_mint, quote_mint)
VALUES
  (
    '8sLbNZoA1cfnvMJLPfp98ZLAnFSYCFApfJKMbiXNLwxj',
    'So11111111111111111111111111111111111111112',
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  ),
  (
    'HfgjZDmexhFVD28Vkb1NbQwWeXP3uDcVTLPjSGHmRHhL',
    'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  ),
  (
    '93MjUKNKxazKmgS3GBX2Gj2BttEjJUyi7NYeyDHdHSc2',
    'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  )
ON CONFLICT (address) DO NOTHING;
